version: '3.'

services:
  flyboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flyboard
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./posts:/app/posts
      - ./blog.settings:/app/blog.settings
      - ./admin.settings:/app/admin.settings
    environment:
      - NATS_URL=${NATS_URL:-}
      - BLOG_ECH_KEY=${BLOG_ECH_KEY:-}
      - BLOG_ECH_DIR=${BLOG_ECH_DIR:-}
    restart: unless-stopped
