services:
  flyboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flyboard
    ports:
      - "${FLYBOARD_PORT:-8888}:8888/tcp"
      - "${FLYBOARD_PORT:-8888}:8888/udp"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./posts:/app/posts
      - ./img:/app/img
      - ./ech:/app/ech
    environment:
      - BLOG_ROOT=/app
#      - NATS_URL=${NATS_URL:-}
      - BLOG_ECH_KEY=${BLOG_ECH_KEY:-/app/ech/server.ech}
      - BLOG_ECH_DIR=${BLOG_ECH_DIR:-/app/ech}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1GB

